# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, attoparsec, binary, blazeHtml, blazeMarkup, exceptions
, filepath, foldl, hakyll, lens, pandoc, pandocTypes, parsec, pipes
, pipesAttoparsec, pipesBytestring, pipesGroup, pipesSafe
, pipesShell, pipesText, split, strict, temporary, text, time
, transformers, yuicompressor
}:

cabal.mkDerivation (self: {
  pname = "newartisans";
  version = "1.0.0";
  src = builtins.filterSource (path: type: type != "unknown") ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [
    attoparsec binary blazeHtml blazeMarkup exceptions filepath foldl
    hakyll lens pandoc pandocTypes parsec pipes pipesAttoparsec
    pipesBytestring pipesGroup pipesSafe pipesShell pipesText split
    strict temporary text time transformers yuicompressor
  ];
  meta = {
    homepage = "http://newartisans.com/";
    description = "Lost in Technopolis";
    license = self.stdenv.lib.licenses.unfree;
    platforms = self.ghc.meta.platforms;
  };
})
