#!/bin/bash
exec rclone sync -v                                             \
       ./result/share/html/newartisans                          \
       fastmail:/johnw.newartisans.com/files/newartisans
